version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    restart: on-failure
    ports:
      - "80:80"
    volumes:
      - ./nginx/log:/var/log/nginx
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - elk

  elasticsearch:
    container_name: elasticsearch
    restart: on-failure
    ports:
      - "9200:9200"
      - "9300:9300"
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    volumes:
      - /var/log/elasticsearch:/var/log/elasticsearch
    networks:
      - elk

  kibana:
    container_name: kibana
    build:
      context: ./kibana
      dockerfile: Dockerfile
    ports:
      - "5601:5601"
    restart: on-failure
    networks:
      - elk

  logstash:
    container_name: logstash
    build:
      context: ./logstash
      dockerfile: Dockerfile
    restart: on-failure
    ports:
      - "5044:5044"
    volumes:
      - /opt/logstash/conf:/opt/logstash/conf
    networks:
      - elk

  filebeat:
    container_name: filebeat
    restart: on-failure
    build:
      context: ./filebeat
      dockerfile: Dockerfile
    depends_on:
      - elasticsearch
      - kibana
      - logstash
    volumes:
      - /var/log/nginx:/var/log/nginx
    networks:
      - elk

networks:
  elk:
    external: true