version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    hostname: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx/log:/var/log/nginx
    networks:
      - default
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 1m30s
      timeout: 10s
      retries: 3
      start_period: 40s
  filebeat:
    build:
      context: ./filebeat
      dockerfile: Dockerfile
    container_name: filebeat
    hostname: filebeat
    volumes:
      - ./nginx/log:/var/log/nginx
    restart: always
    networks:
      - default
  logstash:
    container_name: logstash
    hostname: logstash
    ports:
      - 5044:5044
    build:
      context: ./logstash
      dockerfile: Dockerfile
    volumes:
      - ./logstash/conf:/opt/logstash/conf
    restart: always
    networks:
      - default
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    build:
      context: ./elasticsearch
      dockerfile: Dockerfile
    volumes:
      - ./elasticsearch/log:/var/log/elasticsearch
    restart: always
    networks:
      - default
  kibana:
    container_name: kibana
    hostname: kibana
    build:
      context: ./kibana
      dockerfile: Dockerfile
    ports:
      - 5601:5601
    restart: always
    networks:
      - default
networks:
  default:
    external:
      name: elk
